# Generated by Django 5.2.15 on 2026-06-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('A', 'Mode A - Audit de sécurité'), ('B', 'Mode B - Pipeline de développement'), ('C', 'Mode C - Rapport PDF')], db_index=True, max_length=1)),
                ('room_id', models.CharField(db_index=True, help_text='UUID de la Band Room', max_length=64, unique=True)),
                ('audit_id', models.CharField(blank=True, help_text="ID d'audit généré par les agents (ex: SF-AUDIT-20260614-1234)", max_length=50)),
                ('input_type', models.CharField(choices=[('github', 'GitHub Repository'), ('zip', 'ZIP Upload'), ('text', 'Code collé')], max_length=20)),
                ('input_source', models.TextField(blank=True, help_text='URL GitHub ou nom du fichier ZIP')),
                ('project_label', models.CharField(blank=True, help_text='Nom du projet (optionnel)', max_length=200)),
                ('decision', models.CharField(blank=True, help_text='Décision finale (Mode A: VALIDER/CORRIGER/CRITIQUE)', max_length=20)),
                ('final_report', models.TextField(blank=True, help_text="Rapport final de l'agent décisionnel")),
                ('result_json', models.JSONField(default=dict, help_text="Réponse JSON complète de l'orchestrateur")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text="Durée d'exécution en secondes", null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': "Session d'analyse",
                'verbose_name_plural': "Sessions d'analyse",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'mode'], name='api_analysi_created_9f1d22_idx'), models.Index(fields=['status', '-created_at'], name='api_analysi_status_ab66a8_idx')],
            },
        ),
    ]
